chromium: dont block launch on ublock update failures

diff --git a/bin/wrappers/chromium b/bin/wrappers/chromium
--- a/bin/wrappers/chromium
+++ b/bin/wrappers/chromium
@@ -21,31 +21,35 @@ function ublock_check_update() {
 
 	echo -n "[ublock] "
 
-	latest=$(curl --silent --max-time 2.5 'https://api.github.com/repos/gorhill/uBlock/releases/latest' | jq -r '.tag_name')
+	api=$(curl --silent --max-time 2.5 'https://api.github.com/repos/gorhill/uBlock/releases/latest') || {
+		echo "error fetching gh api"
+		return 0 # this should't be a blocker
+	}
+	local latest_tag=$(echo "$api" | jq -r '.tag_name')
+	local latest_url=$(echo "$api" | jq -r '.assets[] | select(.name == "uBlock0.chromium.zip") | .browser_download_url') # hope this dont change
 
-	if [ "$latest" = "" -o "z${latest}" = "znull" ]; then
+	if [ "$latest_tag" = "" -o "z${latest_tag}" = "znull" ]; then
 		echo "json parse fail"
-		return 1 # json parse fail?
+		return 0 # json parse fail? this shouldn't be a blocker
 	fi
 
-	verlt "${ublock_ver}" "${latest}" && {
-		echo "updating to ${latest}"
+	verlt "${ublock_ver}" "${latest_tag}" && {
+		echo "updating to ${latest_tag}"
 
-		local url="https://github.com/gorhill/uBlock/releases/download/${latest}/uBlock0.chromium.zip" # hope this dont change
-		local tmp_zip="/tmp/uBlock0.chromium.${latest}.zip"
-		local new_folder="${ublock_dir}/${latest}"
+		local tmp_zip="/tmp/uBlock0.chromium.${latest_tag}.zip"
+		local new_folder="${ublock_dir}/${latest_tag}"
 
-		curl -# --location --max-time 30.0 "${url}" -o "${tmp_zip}" && {
+		curl -# --location --max-time 30.0 "${latest_url}" -o "${tmp_zip}" && {
 			unzip -t "${tmp_zip}" && {
 				mkdir -p "${new_folder}"
 				unzip -n -d "${new_folder}" "${tmp_zip}"
 
-				echo "[ublock] updated to ${latest}"
+				echo "[ublock] updated to ${latest_tag}"
 			}
 		}
 		rm -f /tmp/uBlock0.chromium.*.zip
 	} || {
-		echo "latest ${latest}"
+		echo "latest ${latest_tag}"
 	}
 }
 
